// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFxaFRVV8rQ-t8hdA6pljNNsBAiVPgZbw',
    appId: '1:634920642002:android:2c2ba6248fbd3c23b3540b',
    messagingSenderId: '634920642002',
    projectId: 'flutter-a-z-05',
    databaseURL: 'https://flutter-a-z-05-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-a-z-05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLNeaPNgvwMbQ7rscLCr2380vN1M-1Auc',
    appId: '1:634920642002:ios:2d01c5377c78e45db3540b',
    messagingSenderId: '634920642002',
    projectId: 'flutter-a-z-05',
    databaseURL: 'https://flutter-a-z-05-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-a-z-05.appspot.com',
    iosClientId: '634920642002-bfqg44tgbfslrrqlbcfbqctf60e3bp7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj07',
  );
}
